import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class JenisProduk extends javax.swing.JFrame {
private Connection con;
private Statement stat;
private PreparedStatement prep;
private ResultSet res;
    /**
     * Creates new form JenisProduk
     */
    public JenisProduk() {
        initComponents();
        update_TabelJenisProduk();
        koneksi();
    }
private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(""+"jdbc:mysql://localhost:3306/p3", "root","");
            stat = con.createStatement();
            }catch (Exception e)
            {  JOptionPane.showMessageDialog(null, e);
        }
    }
 private void bersihkan() {
        
        KodeJenisProduk.setText("");
        NamaJenisProduk.setText("");
        KodeJenisProduk.requestFocus();
    }
public final void update_TabelJenisProduk(){
        try {
            koneksi();
            String query = "Select * from jenisproduk order by Kode_jenis";
            prep = con.prepareStatement(query);
            res = prep.executeQuery();
            TabelJenisProduk.setModel(DbUtils.resultSetToTableModel(res));
    }
    catch (Exception e)
        
        {
            JOptionPane.showMessageDialog(null, e);
        }finally 
        {
            try{ 
                res.close();
                prep.close();
               }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }       
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jMenuItem1 = new javax.swing.JMenuItem();
        jFrame3 = new javax.swing.JFrame();
        JenisProduk = new javax.swing.JButton();
        Produk = new javax.swing.JButton();
        TambahJenisProduk = new javax.swing.JButton();
        BatalJenisProduk = new javax.swing.JButton();
        EditJenisProduk = new javax.swing.JButton();
        HapusJenisProduk = new javax.swing.JButton();
        SimpnJenisProduk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KodeJenisProduk = new javax.swing.JTextField();
        NamaJenisProduk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelJenisProduk = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JenisProduk.setText("Jenis Produk");
        JenisProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisProdukActionPerformed(evt);
            }
        });

        Produk.setText("Produk");
        Produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdukActionPerformed(evt);
            }
        });

        TambahJenisProduk.setText("Tambah");
        TambahJenisProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahJenisProdukActionPerformed(evt);
            }
        });

        BatalJenisProduk.setText("Batal");
        BatalJenisProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalJenisProdukActionPerformed(evt);
            }
        });

        EditJenisProduk.setText("Edit");
        EditJenisProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditJenisProdukActionPerformed(evt);
            }
        });

        HapusJenisProduk.setText("Hapus");
        HapusJenisProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusJenisProdukActionPerformed(evt);
            }
        });

        SimpnJenisProduk.setText("Simpan");
        SimpnJenisProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpnJenisProdukActionPerformed(evt);
            }
        });

        jLabel1.setText("Kode");

        jLabel2.setText("Nama");

        KodeJenisProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeJenisProdukActionPerformed(evt);
            }
        });

        jLabel3.setText("From Jenis Produk");

        jLabel4.setText("Tabel Jenis Produk");

        TabelJenisProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kode", "Nama"
            }
        ));
        TabelJenisProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelJenisProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelJenisProduk);
        TabelJenisProduk.getColumnModel().getColumn(1).setResizable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("JenisProduk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JenisProduk)
                            .addComponent(Produk, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TambahJenisProduk)
                        .addGap(29, 29, 29)
                        .addComponent(EditJenisProduk)
                        .addGap(29, 29, 29)
                        .addComponent(HapusJenisProduk)
                        .addGap(36, 36, 36)
                        .addComponent(SimpnJenisProduk)
                        .addGap(33, 33, 33)
                        .addComponent(BatalJenisProduk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KodeJenisProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NamaJenisProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahJenisProduk)
                    .addComponent(EditJenisProduk)
                    .addComponent(HapusJenisProduk)
                    .addComponent(SimpnJenisProduk)
                    .addComponent(BatalJenisProduk)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(JenisProduk))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(KodeJenisProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NamaJenisProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Produk))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(338, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpnJenisProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpnJenisProdukActionPerformed
try {
                stat.executeUpdate("insert into jenisproduk values("
                                       +"'"+KodeJenisProduk.getText()+"',"
                                       +"'"+NamaJenisProduk.getText()+"')"
                                       );
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
      
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Keteraan error :"+e);
     }
     
     JenisProduk sv = new JenisProduk();
     sv.setLayar(true);        
    }//GEN-LAST:event_SimpnJenisProdukActionPerformed

    private void KodeJenisProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeJenisProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeJenisProdukActionPerformed

    private void JenisProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisProdukActionPerformed
        try { JenisProduk d = new JenisProduk();
            d.setLayar(true);
            this.dispose();}
            catch (Exception e)
            {JOptionPane.showMessageDialog(null, e);}
      
    }//GEN-LAST:event_JenisProdukActionPerformed

    private void ProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdukActionPerformed
        try { Produk d = new Produk();
            d.setLayar(true);
            this.dispose();}
            catch (Exception e)
            {JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_ProdukActionPerformed

    private void TambahJenisProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahJenisProdukActionPerformed
       try {
                stat.executeUpdate("insert into jenisproduk values("
                                       +"'"+KodeJenisProduk.getText()+"',"
                                       +"'"+NamaJenisProduk.getText()+"')"
                                       );
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
      
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Keteraan error :"+e);
     }
     
     JenisProduk sv = new JenisProduk();
     sv.setLayar(true);
    }//GEN-LAST:event_TambahJenisProdukActionPerformed

    private void TabelJenisProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelJenisProdukMouseClicked
        String isi1 = KodeJenisProduk.getText();
        String isi2 = NamaJenisProduk.getText();
        
        
        int baris = TabelJenisProduk.getSelectedRow();
        KodeJenisProduk.setText(TabelJenisProduk.getModel().getValueAt(baris, 0).toString());
        NamaJenisProduk.setText(TabelJenisProduk.getModel().getValueAt(baris, 1).toString());
        
    }//GEN-LAST:event_TabelJenisProdukMouseClicked

    private void EditJenisProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditJenisProdukActionPerformed
        try {
        String isi1 = KodeJenisProduk.getText();
        String isi2 = NamaJenisProduk.getText();
        
        String sql = "Update jenisproduk set Nama_jenis='"+isi2+"' where Kode_jenis='"+isi1+"'";
        prep = con.prepareStatement(sql);
        prep.execute();
        bersihkan();
        JOptionPane.showMessageDialog(null,  "Data sudah diupdate");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Keteraan error:"+e);
    }
    
    JenisProduk sv = new JenisProduk();
    sv.setLayar(true);
    }//GEN-LAST:event_EditJenisProdukActionPerformed

    private void HapusJenisProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusJenisProdukActionPerformed
                String sql = "delete from jenisproduk where Kode_jenis=?";
        try {
            
            prep = con.prepareStatement(sql);
            prep.setString(1, KodeJenisProduk.getText());
            prep.execute();
            JOptionPane.showMessageDialog(null, "Data Telah Dihapus");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Keteraan error:"+e);
        }
        JenisProduk sv = new JenisProduk();
        sv.setLayar(true);
        
    }//GEN-LAST:event_HapusJenisProdukActionPerformed

    private void BatalJenisProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalJenisProdukActionPerformed
        bersihkan ();
    }//GEN-LAST:event_BatalJenisProdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JenisProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JenisProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JenisProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JenisProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JenisProduk().setVisible(true);
            }
        });
    }
    public void setLayar(boolean a){
        new JenisProduk().setVisible(a);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalJenisProduk;
    private javax.swing.JButton EditJenisProduk;
    private javax.swing.JButton HapusJenisProduk;
    private javax.swing.JButton JenisProduk;
    private javax.swing.JTextField KodeJenisProduk;
    private javax.swing.JTextField NamaJenisProduk;
    private javax.swing.JButton Produk;
    private javax.swing.JButton SimpnJenisProduk;
    private javax.swing.JTable TabelJenisProduk;
    private javax.swing.JButton TambahJenisProduk;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
